name: Deploy to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy_dev:
    name: Deploy Dev Environment
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: SSH into VPS and pull dev_app image
        uses: appleboy/ssh-action@master
        with:
          host: 36.50.176.158
          username: root
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "hello"
