name: Deploy to VPS

on:
  push:
    branches:
      - dev
      
jobs:
  deploy_dev:
    name: Deploy Dev Environment
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    
    steps:
      - name: SSH into VPS and pull dev_app image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "hello"
